config/routes.rb
Rails.application.routes.draw do
  resources :journals, only: %i(new create show) do
    resources :entries, only: %i(new create) do
      resource :text_analysis_report, only: %i(show)
    end
    resources :entries_reports, only: %i(index)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :journal
  has_one :text_analysis_report, as: :analysable
  has_one :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :entry
end

app/models/journal.rb
class Journal < ApplicationRecord
  has_many :entries
  has_many :text_anylysis_reports, as: :analysable
  has_many :entries_reports, class_name: 'TextAnalysisReport', through: :entries, source: :text_analysis_report
end

app/models/keywords_report.rb
class KeywordsReport < ApplicationRecord
  belongs_to :text_analysis_report
end

app/models/sentiment_report.rb
class SentimentReport < ApplicationRecord
  belongs_to :text_analysis_report
end

app/models/text_analysis_report.rb
class TextAnalysisReport < ApplicationRecord
  belongs_to :analysable, polymorphic: true
  has_one :sentiment_report
  has_one :keywords_report
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    journal
    @entry = Entry.new
  end

  def create
    entry = Entry.create!(journal: journal, title: entry_params[:title], text: entry_params[:text])
    service = ::Entries::Analyse.call(entry: entry)

    if service.success?
      redirect_to journal_entry_text_analysis_report_path(journal, entry)
    else
      render :new
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :text)
  end

  def journal
    @journal ||= Journal.find(params[:journal_id])
  end
end

app/controllers/entries_reports_controller.rb
class EntriesReportsController < ApplicationController
  def index
    @reports = journal.entries_reports
  end

  private

  def journal
    @journal ||= Journal.find(params[:journal_id])
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def new
    @journal = Journal.new
  end

  def create
    journal = Journal.create!(journal_params)
    redirect_to new_journal_entry_path(journal)
  end

  def show
    
  end

  private

  def journal_params
    params.require(:journal).permit(:name)
  end
end

app/controllers/text_analysis_reports_controller.rb
class TextAnalysisReportsController < ApplicationController
  def index
    entries_reports
  end

  def show
    report
  end

  private

  def journal
    @journal ||= Journal.find(params[:journal_id])
  end

  def entries_reports
    @entries ||= journal.entries_reports
  end

  def entry
    @entry ||= journal.entries.find(params[:entry_id])
  end

  def report
    @report ||= entry.text_analysis_report
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.haml
= form_for [@journal, @entry] do |f|
  = label_tag(:title, "Title")
  = f.text_field :title
  = label_tag(:text, "Text")
  = f.text_area :text
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', entries_path

app/views/entries/index.html.haml
%h1 Listing entries

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @entries.each do |entry|
      %tr
        %td= link_to 'Show', entry
        %td= link_to 'Edit', edit_entry_path(entry)
        %td= link_to 'Destroy', entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entry', new_entry_path

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

app/views/entries/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_entry_path(@entry)
\|
= link_to 'Back', entries_path

app/views/entries_reports/index.haml
%h1 Listing text_analysis_reports

%table.table
  %thead
    %tr
      %th Date range
      %th Sentiment
      %th Positive Score
      %th Neutral Score
      %th Negative Score
      %th Mixed Score
      %th Keywords
    %tbody
    - @reports.each do |report|
      %tr
        %td= "#{report.start_date} - #{report.end_date}"
        %td= report.sentiment_report.sentiment
        %td= report.sentiment_report.positive_score.round(2)
        %td= report.sentiment_report.neutral_score.round(2)
        %td= report.sentiment_report.negative_score.round(2)
        %td= report.sentiment_report.mixed_score.round(2)
        %td= report.keywords_report.keywords.join(', ')

app/views/journals/_form.html.haml
= form_for @journal do |f|
  = label_tag(:name, "Journal Name")
  = f.text_field :name
  - if @journal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@journal.errors.count, "error")} prohibited this journal from being saved:"
      %ul
        - @journal.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/journals/edit.html.haml
%h1 Editing journal

= render 'form'

= link_to 'Show', @journal
\|
= link_to 'Back', journals_path

app/views/journals/index.html.haml
%h1 Listing journals

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @journals.each do |journal|
      %tr
        %td= link_to 'Show', journal
        %td= link_to 'Edit', edit_journal_path(journal)
        %td= link_to 'Destroy', journal, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Journal', new_journal_path

app/views/journals/new.html.haml
%h1 New journal

= render 'form'

= link_to 'Back', journals_path

app/views/journals/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_journal_path(@journal)
\|
= link_to 'Back', journals_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwsComprehendDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/text_analysis_reports/_form.html.haml
= form_for @text_analysis_report do |f|
  - if @text_analysis_report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@text_analysis_report.errors.count, "error")} prohibited this text_analysis_report from being saved:"
      %ul
        - @text_analysis_report.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/text_analysis_reports/edit.html.haml
%h1 Editing text_analysis_report

= render 'form'

= link_to 'Show', @text_analysis_report
\|
= link_to 'Back', text_analysis_reports_path

app/views/text_analysis_reports/index.html.haml
%h1 Listing text_analysis_reports

%table.table
  %thead
    %tr
      %th Date range
      %th Sentiment
      %th Positive Score
      %th Neutral Score
      %th Negative Score
      %th Mixed Score
      %th Keywords
    %tbody
    - @reports.each do |report|
      %tr
        %td= "#{report.start_date} - #{report.end_date}"
        %td= report.sentiment_report.sentiment
        %td= report.sentiment_report.positive_score.round(2)
        %td= report.sentiment_report.neutral_score.round(2)
        %td= report.sentiment_report.negative_score.round(2)
        %td= report.sentiment_report.mixed_score.round(2)
        %td= report.keywords_report.keywords.join(', ')

app/views/text_analysis_reports/new.html.haml
%h1 New text_analysis_report

= render 'form'

= link_to 'Back', text_analysis_reports_path

app/views/text_analysis_reports/show.html.haml
%table.table
  %thead
    %tr
      %th Date range
      %th Sentiment
      %th Positive Score
      %th Neutral Score
      %th Negative Score
      %th Mixed Score
      %th Keywords
    %tbody
      %tr
        %td= "#{@report.start_date} - #{@report.end_date}"
        %td= @report.sentiment_report.sentiment
        %td= @report.sentiment_report.positive_score.round(2)
        %td= @report.sentiment_report.neutral_score.round(2)
        %td= @report.sentiment_report.negative_score.round(2)
        %td= @report.sentiment_report.mixed_score.round(2)
        %td= @report.keywords_report.keywords.join(', ')